# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push (all branches) or pull request (only main)
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    container: docker://sebj101/qtnm_deps_2:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Build Package
      - name: Build
        run: |
          source /opt/root/bin/thisroot.sh
          mkdir build && cd build
          cmake ..
          make

      # Run Tests
      - name: RunTests
        run: |
          cd build/bin
          ./testXSecs -o crosssections.root
          python3 ../../test/crossSectionTestPlots.py --input crosssections.root --output crosssections

      # Upload test results
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/bin/*.png
            build/bin/*.pdf
            build/bin/*.root